version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: framgia/laravel-php-fpm
        container_name: project_app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: project_app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage/database:/var/www/storage/database
        networks:
            - app-network

    webserver:
        image: nginx
        container_name: project_webserver
        restart: always
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
